### ISSUE TITLE
Bitte das SSL-Zertifikat der Webseite erneuern

### ISSUE THREAD

**Issue by krapas170** [LoadingByte/sts-inquiry#1]
Deine Webseite wird als nicht mehr sicher gekennzeichnet, weil dein SSL-Zertifikat am 10. Oktober abgelaufen ist. Somit erhalten alle die Meldung, dass die Webseite nicht sicher ist. Wollte dich da bloß informieren.

**Comment by LoadingByte** [comment]
Vielen Dank für die Nachricht! Ist seit ein paar Tagen zum Glück behoben, der Cronjob wollte nicht...
