### ISSUE TITLE
Allow multiple nameexcl and nameincl values, e.g., by splitting at ","

### ISSUE THREAD

**Issue by cmfcmf** [LoadingByte/sts-inquiry#2]

**Comment by LoadingByte** [comment]
In fact, this is already possible by using | as the delimiter (as indicated by nameexcl's sample text). Both fields have OR semantics when supplying multiple values, i.e., the name has to include A or B, or must neither include A nor B.

Do you propose additional logical connectors?

**Comment by cmfcmf** [comment]
Ahh, I totally missed that, sorry!
